version: '3.4'

services:

  cordial_test:
    build:
      context: .
      target: cordial_test
      network: host
    network_mode: host
    environment:
      AWS_SECRET_KEY_ID:
      AWS_SECRET_KEY:
      AWS_REGION:
      AWS_OUTPUT_FORMAT: json

  cordial_dev:
    build:
      context: .
      target: cordial_dev
      network: host
    environment:
      DISPLAY: $DISPLAY
      QT_GRAPHICSSYSTEM: native
      ROS_DISTRO: kinetic
      ROS_MASTER_URI: $ROS_MASTER_URI
      IS_DOCKER_ENV: "true"
    privileged: true
    network_mode: host
    devices: 
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    volumes:
      - aws_config:/root/.aws/
      - pycharm_config:/root/.PyCharmCE2020.2.1/
      - ros_logs:/root/.ros/log
      - scratch:/root/scratch/
      - workspace:/root/catkin_ws/
      - visual_code_plugins:/root/.vscode/
      - visual_code_user_data:/root/.visual_code/
      - ./shared/:/root/shared/
      - ~/.gitconfig/:/root/.gitconfig/:ro
      - ~/.vimrc/:/root/.vimrc/:ro
      - ~/.vim/:/root/.vim/:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /root/

volumes:
  aws_config:
  pycharm_config:
  ros_logs:
  scratch:
  workspace:
  visual_code_user_data:
  visual_code_plugins:
