on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test_cordial:
    name: Test Cordial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set branch name for pull request
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::${{github.event.pull_request.head.ref}}"
      - name: Set branch name
        if: github.event_name != 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
      - name: Echo branch name
        run: echo ${BRANCH_NAME}

      - name: Build Docker container
        run: docker-compose build --build-arg cordial_branch=${BRANCH_NAME} cordial_test
        working-directory: ./docker

      - name: Run the Docker container
        run: docker-compose run cordial_test /entrypoint.bash
        working-directory: ./docker
        env:
          AWS_SECRET_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_REGION: us-west-1
